### ISSUE TITLE
FreeBSD pip/virtualenv installations fail as py36-{pip,virtualenv} are no longer upstream

### ISSUE THREAD

**Issue by rick-pri** [xaque208/puppet-python#18]
For now I've had to set `pip` to false and roll our own `exec`s for `pip` and `virtualenv`.  I'll provide the code below that we use for ensuring `pip` (noting that we specify in `heira` data the python version to pass to this module, so `36` if we want python 3.6 to be installed)

```
  exec { 'ensurepip':
    command => "/usr/local/bin/python${version[0]}.${version[1]} -m ensurepip",
    creates => "/usr/local/bin/pip-${version[0]}.${version[1]}",
    require => Package["python${version}"],
  }
```

**Comment by xaque208** [comment]
Thank you for the report.  Can you elaborate on why this change is required?  Does this come up because you are installing a different python version than the default?

For context, on my FreeBSD systems, I set `DEFAULT_VERSIONS=python=3.6` in my ports builds, and then specify `36` in hiera as you do also, so that I have the `py360{pip,virtualenv}` packages available.

**Comment by rick-pri** [comment]
Hi Zack, 

As far as I understand it, the default package manager in Puppet for FreeBSD is pkg(ng), so when puppet tries to interpret the following:

```
class { 'python' :
  version    => '36',
  pip        => true,
  dev        => true,
  virtualenv => true,
}
```

the module checks the valid versions in the `FreeBSD.yaml` and then gets:

```
  '36':
    virtualenv_package: 'py36-virtualenv'
    virtualenv_cmd: 'virtualenv-3.6'
    pip_package: 'py36-pip'
    pip_cmd: 'pip-3.6'
```

From here `pkg` will try to install `py36-pip` which doesn't exist using the ensure_pip function which doesn't override the pkg provider default.  As py36-pip doesn't exist upstream (and we've not yet built our poudriere infrastructure to provide our own ports built packages) the python module fails.

**Comment by xaque208** [comment]
Ah yes, you are correct.  The only reason I'm able to install python 3.6 on my systems is due to the fact that I'm building my own ports with poudriere.  How have you gotten python3.6 installed?

To get poudriere going, there is a module that could help. 
 https://github.com/xaque208/puppet-poudriere

Maybe this module could support something like `pyenv`, which is like `rbenv`, but for python to get installed versions that are not available as packages.

**Comment by rick-pri** [comment]
Hi Zack,

Sorry for the delay in responding (I'm not getting the emails from github just for this issue for some reason.)  I rolled back from 3.6 to 3.5, but I was using this module to deploy to FreeBSD 11 client servers and it pulls down the `python36`  package just fine because it's available.

I'd really like, and we have the requirements for it, to get poudriere up and running in our infrastructure.  But in the mean time I've got something like the above `exec` working for both the require pip step and installing the virtualenv.

The `pyenv` approach sounds interesting; I've actually had a play about with this on Ubuntu.  

Kind regards,
Richard

**Comment by rick-pri** [comment]
Hi Zack.  Let's close this.  We could use the module now, for python 3.6 for example, because the upstream has switch to providing py36 packages, but if we wanted to rebuild our older projects which have still only been tested as working with python 3.5 we couldn't because those packages no longer exist upstream.

This is a seemingly intractable problem that we will always face but for which we have an automated version of a manual solution as described in my first post explaining the issue.
